import { PROJECT_IDS } from "./projects.seed.js";
import { USER_IDS } from "./users.seed.js";

const tasks = [
  {
    projectId: PROJECT_IDS.raceCar,
    assignedToId: USER_IDS.development,
    title: "Finalize chassis design",
    description: "Review the chassis geometry and approve it for manufacturing.",
    status: "IN_PROGRESS",
    priority: "HIGH",
  },
  {
    projectId: PROJECT_IDS.raceCar,
    assignedToId: USER_IDS.salma,
    title: "Prepare manufacturing drawings",
    description: "Produce dimensioned drawings for all chassis mounting points.",
    status: "TODO",
    priority: "HIGH",
  },
  {
    projectId: PROJECT_IDS.raceCar,
    assignedToId: USER_IDS.omar,
    title: "Test sensor wiring",
    description: "Verify continuity and signal quality for the installed sensors.",
    status: "DONE",
    priority: "MEDIUM",
  },
  {
    projectId: PROJECT_IDS.raceCar,
    assignedToId: USER_IDS.mariam,
    title: "Book track testing session",
    description: "Confirm the venue, date, safety equipment, and transport plan.",
    status: "TODO",
    priority: "MEDIUM",
  },
  {
    projectId: PROJECT_IDS.raceCar,
    assignedToId: null,
    title: "Document test results",
    description: "Create a template for recording track-test observations.",
    status: "TODO",
    priority: "LOW",
  },
  {
    projectId: PROJECT_IDS.sponsorship,
    assignedToId: USER_IDS.salma,
    title: "Update sponsorship brochure",
    description: "Refresh the team statistics, benefits, and vehicle images.",
    status: "IN_PROGRESS",
    priority: "HIGH",
  },
  {
    projectId: PROJECT_IDS.sponsorship,
    assignedToId: USER_IDS.development,
    title: "Review technical presentation",
    description: "Check technical claims and competition information for accuracy.",
    status: "TODO",
    priority: "MEDIUM",
  },
  {
    projectId: PROJECT_IDS.sponsorship,
    assignedToId: USER_IDS.youssef,
    title: "Build sponsor contact list",
    description: "Organize prospective sponsors by industry and outreach priority.",
    status: "DONE",
    priority: "HIGH",
  },
  {
    projectId: PROJECT_IDS.sponsorship,
    assignedToId: null,
    title: "Plan sponsor workshop",
    description: "Draft the agenda and required materials for the sponsor workshop.",
    status: "TODO",
    priority: "LOW",
  },
  {
    projectId: PROJECT_IDS.sponsorship,
    assignedToId: USER_IDS.salma,
    title: "Send monthly sponsor report",
    description: "Summarize progress, milestones, and upcoming activities.",
    status: "DONE",
    priority: "MEDIUM",
  },
  {
    projectId: PROJECT_IDS.telemetry,
    assignedToId: USER_IDS.omar,
    title: "Define telemetry packet format",
    description: "Document fields, units, frequencies, and validation rules.",
    status: "DONE",
    priority: "HIGH",
  },
  {
    projectId: PROJECT_IDS.telemetry,
    assignedToId: USER_IDS.development,
    title: "Create dashboard layout",
    description: "Build the initial dashboard layout for live and historical data.",
    status: "IN_PROGRESS",
    priority: "HIGH",
  },
  {
    projectId: PROJECT_IDS.telemetry,
    assignedToId: USER_IDS.mariam,
    title: "Prepare track map data",
    description: "Collect and normalize coordinates for the testing circuit.",
    status: "TODO",
    priority: "MEDIUM",
  },
  {
    projectId: PROJECT_IDS.telemetry,
    assignedToId: USER_IDS.hana,
    title: "Add alert thresholds",
    description: "Configure warnings for temperature, voltage, and pressure limits.",
    status: "IN_PROGRESS",
    priority: "MEDIUM",
  },
  {
    projectId: PROJECT_IDS.telemetry,
    assignedToId: null,
    title: "Write dashboard user guide",
    description: "Explain dashboard views, filters, alerts, and exports.",
    status: "TODO",
    priority: "LOW",
  },
  {
    projectId: PROJECT_IDS.logistics,
    assignedToId: USER_IDS.mariam,
    title: "Confirm vehicle transport",
    description: "Finalize the transporter booking and collection schedule.",
    status: "DONE",
    priority: "HIGH",
  },
  {
    projectId: PROJECT_IDS.logistics,
    assignedToId: USER_IDS.salma,
    title: "Create equipment checklist",
    description: "List tools, spare parts, safety equipment, and team supplies.",
    status: "IN_PROGRESS",
    priority: "HIGH",
  },
  {
    projectId: PROJECT_IDS.logistics,
    assignedToId: USER_IDS.youssef,
    title: "Reserve team accommodation",
    description: "Confirm rooms, arrival times, and payment requirements.",
    status: "TODO",
    priority: "MEDIUM",
  },
  {
    projectId: PROJECT_IDS.logistics,
    assignedToId: null,
    title: "Prepare emergency contacts",
    description: "Compile organizer, medical, transport, and team contacts.",
    status: "TODO",
    priority: "MEDIUM",
  },
  {
    projectId: PROJECT_IDS.logistics,
    assignedToId: USER_IDS.mariam,
    title: "Publish competition itinerary",
    description: "Share the final travel and event schedule with the full team.",
    status: "DONE",
    priority: "LOW",
  },
].map((task, index) => ({
  id: `40000000-0000-4000-8000-${String(index + 1).padStart(12, "0")}`,
  ...task,
}));

export async function seedTasks(db) {
  for (const task of tasks) {
    await db.task.upsert({
      where: { id: task.id },
      update: {
        projectId: task.projectId,
        assignedToId: task.assignedToId,
        title: task.title,
        description: task.description,
        status: task.status,
        priority: task.priority,
      },
      create: task,
    });
  }
}
